name: 'Validate cluster'
description: "Workflow that wait for cluster to be in a ready state"
inputs:
  cluster_name:
    description: "Name of the cluster"
    required: true
  kops_state:
    description: "Bucket with kops state"
    required: true
  timeout:
    description: "Maximum time to wait for cluster to be ready"
    default: "20m"
runs:
  using: "composite"
  steps:
    - name: Validate cluster
      shell: bash
      run: |
        ./kops validate cluster \
          ${{ inputs.cluster_name }} \
          --state ${{ inputs.kops_state }} \
          --wait ${{ inputs.timeout }} \
          --count 3
