name: 'Cleanup kops cluster'
description: "Workflow that cleans up kops cluster"
inputs:
  cluster_name:
    description: "Name of the cluster to delete"
    required: true
  kops_state:
    description: "Bucket with kops state"
    required: true
runs:
  using: "composite"
  steps:
    - name: Delete cluster
      uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3.0.0
      with:
        timeout_minutes: 30
        max_attempts: 10
        polling_interval_seconds: 120
        command: |
          ./kops delete cluster \
            ${{ inputs.cluster_name }} \
            --state ${{ inputs.kops_state }} \
            --yes
